[_]
schema-version = "0.2"

[io.buildpacks]
exclude = [
    ".gcloudignore",
    ".git",
    ".github",
    ".gitignore",
    ".venv",
    "README.md",
    "__pycache__",
    "build_container.py",
    "data",
    "project.toml",
    "run_webhooks.py",
    "test*",
]
