name: Project Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    uses: ./.github/workflows/test.yml
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
