name: Deploy to Google Cloud Functions
on:
  workflow_call:
    inputs:
      function_name:
        required: true
        type: string
      region:
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Deploy to environment
        id: deploy
        run: |
          gcloud functions deploy ${{ inputs.function_name }} \
            --gen2 \
            --region=${{ inputs.region }} \
            --runtime=python311 \
            --source=. \
            --entry-point=serve \
            --trigger-http
      - name: Run post-deployment health check
        run: |
          pip install requests
          python -m run_webhooks https://${{ inputs.region}}-${{ env.GCP_PROJECT }}.cloudfunctions.net/${{ inputs.function_name }}
