name: Publish container image
on:
  workflow_call:
    inputs:
      registry:
        default: ""
        required: false
        type: string
      repository:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.password }}
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install setuptools-scm
        run: pip install --upgrade setuptools setuptools-scm
      - name: Discover image tag version
        id: tag
        env:
          REPO: ${{ inputs.CONTAINER_REPO }}
        run: |
          echo "image_tag=${REPO}:$(python -m setuptools_scm --strip-dev)" >> "${GITHUB_OUTPUT}"
      - name: Publish
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.tag.outputs.image_tag }}
    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}
