name: Publish container image
on:
  workflow_dispatch:
env:
  REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
  REPO: ${{ vars.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_REPO }}
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u $ --password-stdin
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install setuptools-scm
        run: pip install --upgrade setuptools setuptools-scm
      - name: Build
        run: |
          IMAGE_TAG=${REPO}:$(python -m setuptools_scm --strip-dev)
          echo "IMAGE_TAG=${IMAGE_TAG}" >> "${GITHUB_ENV}"
          docker build --tag ${IMAGE_TAG} .
      - name: Publish
        run: docker push ${IMAGE_TAG}
