name: Publish container image
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
env:
  REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ vars.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_REPO }}:${{ inputs.version }}
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u $ --password-stdin
      - name: Set up pack
        uses: buildpacks/github-actions/setup-pack@v5.0.0
      - name: Build
        run: python build_container.py $IMAGE_TAG
      - name: Publish
        run: docker push $IMAGE_TAG
