name: Release
on:
  release:
    types:
      - released
jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    uses: ./.github/workflows/publish-container-image.yml
    secrets:
      password: ${{ secrets.DOCKERHUB_PASSWORD }}
    with:
      repository: ${{ vars.CONTAINER_REPO }}
      username: ${{ vars.DOCKERHUB_USERNAME }}
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
    with:
      image: ${{ needs.build.outputs.image_tag }}
      region: ${{ vars.GCP_REGION }}
      service_env: ${{ vars.GCP_SERVICE_ENV }}
      service_name: ${{ vars.GCP_SERVICE_NAME }}
